name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Nim ${{ matrix.nim }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [2.0.14, 2.2.0, 2.2.2, devel]
    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: ${{ matrix.nim }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup
      run: |
        sudo apt update
        sudo apt install -y make 
        sudo make install_mkcert
        mkcert -install
        mkcert example.com "*.example.com" example.test localhost 127.0.0.1 ::1
        nimble install -y --depsOnly
        cat .env >> $GITHUB_ENV
      #  cat ./example.com+5.pem
      #  cat ./example.com+5-key.pem
      #  echo $HYPERX_TEST_CERTFILE
      #  echo $HYPERX_TEST_KEYFILE
    - name: Run Tests
      run: |
        nimble test
    - name: Run Functional Tests
      run: |
        (nimble funcserve &)
        sleep 10s
        nimble functest
    - name: Run Functional Insecure Tests
      run: |
        (nimble funcserveinsec &)
        sleep 10s
        nimble functestinsec
    - name: Run Functional Multi-Thread Tests
      run: |
        (nimble funcservemultithread &)
        sleep 10s
        nimble functestmultithread
    - name: Run Examples
      run: |
        (nimble serve2 &)
        sleep 10s
        nimble testexamples
    - name: Run h2spec
      run: |
        curl -JLO "https://github.com/nitely/nim-hyperx/releases/download/v0.1.20/h2spec"
        chmod +x ./h2spec
        nimble h2spec
        nimble h2spec
        nimble h2spec
    - name: Run h2load
      run: |
        sudo apt install -y nghttp2-client
        nimble h2load
        nimble h2load2
