name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Nim ${{ matrix.nim }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [2.0.0]
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        docker pull nimlang/nim:${{ matrix.nim }}
        docker run --rm -v `pwd`:/usr/src/app -w /usr/src/app nimlang/nim:${{ matrix.nim }} \
        /bin/bash -c "git config --global --add safe.directory /usr/src/app && \ 
          apt install libnss3-tools && \
          curl -JLO \"https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-arm64\" && \
          chmod +x mkcert-v*-linux-amd64 && \
          cp mkcert-v*-linux-amd64 /usr/local/bin/mkcert && \
          mkcert -install && \
          mkcert example.com \"*.example.com\" example.test localhost 127.0.0.1 ::1 && \
          nimble install -y && \
          nimble test"
