name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Nim ${{ matrix.nim }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [2.0.0]
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        docker pull nimlang/nim:${{ matrix.nim }}
        docker run --env-file .env  --rm -v `pwd`:/usr/src/app -w /usr/src/app nimlang/nim:${{ matrix.nim }} \
        /bin/bash -c "git config --global --add safe.directory /usr/src/app && \
          apt update && \
          apt install -y make && \ 
          make install_mkcert && \
          nimble install -y && \
          nimble test"
    - name: Run h2spec
      run: |
        docker pull nimlang/nim:${{ matrix.nim }}
        docker run --env-file .env  --rm -v `pwd`:/usr/src/app -w /usr/src/app nimlang/nim:${{ matrix.nim }} \
        /bin/bash -c "git config --global --add safe.directory /usr/src/app && \
          apt update && \
          apt install -y make && \ 
          make install_mkcert && \
          nimble install -y && \
          (nimble serve &) && \
          sleep 10s && \
          curl -JLO \"https://github.com/summerwind/h2spec/releases/download/v2.6.0/h2spec_linux_amd64.tar.gz\" && \
          tar -xvf h2spec_linux_amd64.tar.gz && \
          chmod +x ./h2spec && \
          ./h2spec --tls --port 4443 --strict"
    - name: Run h2load
      run: |
        docker pull nimlang/nim:${{ matrix.nim }}
        docker run --env-file .env  --rm -v `pwd`:/usr/src/app -w /usr/src/app nimlang/nim:${{ matrix.nim }} \
        /bin/bash -c "git config --global --add safe.directory /usr/src/app && \
          apt update && \
          apt install -y make && \ 
          make install_mkcert && \
          nimble install -y && \
          (nimble serve2 &) && \
          sleep 10s && \
          apt install -y g++ clang make binutils autoconf automake \
            autotools-dev libtool pkg-config \
            zlib1g-dev libssl-dev libxml2-dev libev-dev \
            libevent-dev libjansson-dev \
            libc-ares-dev libjemalloc-dev libsystemd-dev \
            ruby-dev bison libelf-dev && \
          curl -JLO \"https://github.com/nghttp2/nghttp2/releases/download/v1.61.0/nghttp2-1.61.0.tar.gz\" && \
          tar -xvf nghttp2-1.61.0.tar.gz && \
          cd /usr/src/app/nghttp2-1.61.0 && \
          ./configure --enable-app && \
          make && \
          cd /usr/src/app/nghttp2-1.61.0/src && \
          chmod +x ./h2load && \
          ./h2load -n100000 -c100 -m10 https://127.0.0.1:4443 | tee /dev/tty | grep "100000 2xx""
