name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Nim ${{ matrix.nim }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [2.0.0]
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: |
        docker pull nimlang/nim:${{ matrix.nim }}
        docker run --env-file .env  --rm -v `pwd`:/usr/src/app -w /usr/src/app nimlang/nim:${{ matrix.nim }} \
        /bin/bash -c "git config --global --add safe.directory /usr/src/app && \ 
          make install_mkcert && \
          nimble install -y && \
          nimble test"
