name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Nim ${{ matrix.nim }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [2.0.0]
    steps:
    - uses: actions/checkout@v2
    - name: Run h2load
      run: |
        docker pull nimlang/nim:${{ matrix.nim }}
        docker run --env-file .env  --rm -v `pwd`:/usr/src/app -w /usr/src/app nimlang/nim:${{ matrix.nim }} \
        /bin/bash -c "git config --global --add safe.directory /usr/src/app && \
          apt update && \
          apt install -y make && \ 
          make install_mkcert && \
          nimble install -y && \
          (nimble serve2 &) && \
          sleep 10s && \
          apt install -y build-essential procps curl file git && \
          curl -fsSL \"https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh\" && \
          brew install nghttp2 && \
          h2load -n100000 -c100 -m10 https://127.0.0.1:4443 | tee /dev/tty | grep \"100000 2xx\""
